const standard: string[] = [
  "The worst thing to say on a first date",
  "A terrible name for a new superhero",
  "The real reason dinosaurs went extinct",
  "What aliens would be surprised to learn about humans",
  "The worst gift to bring to a wedding",
  "A rejected flavor of ice cream",
  "The secret ingredient in grandma's cookies",
  "A terrible excuse for being late to work",
  "The worst place to hide during hide and seek",
  "An inappropriate time to yell 'Surprise!'",
  "The worst thing to say during a job interview",
  "A terrible name for a new perfume",
  "What dogs think about all day",
  "The worst thing to hear from your doctor",
  "An unconventional use for a banana",
  "The real reason Santa is always jolly",
  "A terrible slogan for a funeral home",
  "What fish think about while swimming",
  "The worst thing to say when meeting your in-laws",
  "An unusual item to find in someone's search history",
  "The worst theme for a child's birthday party",
  "A surprising discovery at the bottom of the ocean",
  "The worst subject for a motivational poster",
  "An odd thing to find in your grandmother's attic",
  "The worst pickup line ever",
  "A terrible name for a new restaurant",
  "The real reason cats always land on their feet",
  "An unexpected item to find in a time capsule from 2023",
  "The worst song to play at a wedding",
  "A strange way to quit your job",
];

const adultDirty: string[] = [
  "The worst thing to say during sex",
  "A terrible name for a porn star",
  "The real reason strip clubs have dark lighting",
  "What aliens would be surprised to learn about human fetishes",
  "The worst sex toy to bring to a bachelor party",
  "A rejected flavor of edible underwear",
  "The secret ingredient in adult-themed baked goods",
  "A terrible excuse for having a sex toy collection",
  "The worst place to get caught having sex",
  "An inappropriate time to say 'I'm coming!'",
  "The worst thing to say during a one-night stand",
  "A terrible name for an adult film",
  "What dogs think about their owners' sex lives",
  "The worst thing to hear from your lover",
  "An unconventional use for a dildo",
  "The real reason Santa enjoys his 'naughty' list",
  "A terrible slogan for a sex shop",
  "What fish think about underwater orgies",
  "The worst thing to say during a threesome",
  "An unusual item to find in someone's porn search history",
  "The worst theme for a swingers' party",
  "A surprising discovery in an adult toy store",
  "The worst subject for an erotic novel",
  "An odd thing to find in your lover's nightstand",
  "The worst pickup line in a bar",
  "A terrible name for a strip club",
  "The real reason why people use sex swings",
  "An unexpected item to find in a swinger's time capsule",
  "The worst song to play during sex",
  "A strange way to break up with someone",
];

const familyFriendly: string[] = [
  "The worst thing to say to your teacher",
  "A terrible name for a superhero's sidekick",
  "The real reason dinosaurs disappeared",
  "What aliens would be surprised to learn about human habits",
  "The worst gift to bring to a kid's birthday party",
  "A rejected flavor of candy",
  "The secret ingredient in grandma's famous pie",
  "A terrible excuse for not doing homework",
  "The worst place to hide during tag",
  "An inappropriate time to shout 'Happy Birthday!'",
  "The worst thing to say at a parent-teacher conference",
  "A terrible name for a new toy",
  "What dogs think about their owners",
  "The worst thing to hear from your babysitter",
  "An unconventional use for a banana in a craft project",
  "The real reason Santa is so happy",
  "A terrible slogan for a toy store",
  "What fish think about in their tanks",
  "The worst thing to say to your friend's parents",
  "An unusual item to find in someone's backpack",
  "The worst theme for a school dance",
  "A surprising discovery in a toy chest",
  "The worst subject for a children's book",
  "An odd thing to find in your attic",
  "The worst pickup line on the playground",
  "A terrible name for a new kids' restaurant",
  "The real reason cats have nine lives",
  "An unexpected item to find in a 2023 time capsule",
  "The worst song to play at a kids' party",
  "A strange way to tell your teacher you're sick",
];

export { standard, adultDirty, familyFriendly };
