const prompts: string[] = [
    "Name a country that starts with the letter 'Z'.",
    "What is the capital city of Japan?",
    "Who painted the Mona Lisa?",
    "What year did the first moon landing occur?",
    "What is the largest planet in our solar system?",
    "Who wrote the play 'Romeo and Juliet'?",
    "What is the chemical symbol for gold?",
    "Which ocean is the largest on Earth?",
    "What is the fastest land animal?",
    "Who invented the telephone?",
    "What is the tallest mountain in the world?",
    "What is the main ingredient in guacamole?",
    "Who was the first President of the United States?",
    "What is the largest organ in the human body?",
    "Which planet is known as the Red Planet?",
    "What is the capital of Australia?",
    "Who wrote '1984'?",
    "What is the smallest prime number?",
    "Which element has the atomic number 1?",
    "What is the national animal of Scotland?",
    "Who painted 'The Starry Night'?",
    "What is the largest mammal in the world?",
    "What is the currency of Japan?",
    "Who discovered penicillin?",
    "What is the longest river in the world?",
    "What is the main language spoken in Brazil?",
    "Who is known as the father of computer science?",
    "What is the boiling point of water in Celsius?",
    "Which country is home to the Great Barrier Reef?",
    "Who wrote 'To Kill a Mockingbird'?",
  ];
  export default prompts;