const prompts: string[] = [
  "The worst thing to say on a first date",
  "A terrible name for a new superhero",
  "The real reason dinosaurs went extinct",
  "What aliens would be surprised to learn about humans",
  "The worst gift to bring to a wedding",
  "A rejected flavor of ice cream",
  "The secret ingredient in grandma's cookies",
  "A terrible excuse for being late to work",
  "The worst place to hide during hide and seek",
  "An inappropriate time to yell 'Surprise!'",
  "The worst thing to say during a job interview",
  "A terrible name for a new perfume",
  "What dogs think about all day",
  "The worst thing to hear from your doctor",
  "An unconventional use for a banana",
  "The real reason Santa is always jolly",
  "A terrible slogan for a funeral home",
  "What fish think about while swimming",
  "The worst thing to say when meeting your in-laws",
  "An unusual item to find in someone's search history",
  "The worst theme for a child's birthday party",
  "A surprising discovery at the bottom of the ocean",
  "The worst subject for a motivational poster",
  "An odd thing to find in your grandmother's attic",
  "The worst pickup line ever",
  "A terrible name for a new restaurant",
  "The real reason cats always land on their feet",
  "An unexpected item to find in a time capsule from 2023",
  "The worst song to play at a wedding",
  "A strange way to quit your job",
];

export default prompts;